# Generated by Django 2.1.1 on 2020-09-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_name', models.CharField(blank=True, default='', max_length=100)),
                ('lat', models.FloatField(blank=True, default=0)),
                ('lng', models.FloatField(blank=True, default=0)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('business_hour', models.CharField(blank=True, default='', max_length=100)),
                ('temp_review_count', models.IntegerField(blank=True, default=0, null=True)),
                ('temp_total_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('logo', models.ImageField(default='bakery/image/logo_default.png', upload_to='logo_photo_path')),
                ('city', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('row_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='bakery/bread_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('rating', models.FloatField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bakeries.Bakery')),
            ],
        ),
    ]
